# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0003_auto_20180109_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eignface', models.TextField()),
                ('mean', models.TextField()),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrol', to='pegawai.Pegawai')),
            ],
        ),
    ]
