# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_auto_20180109_1512'),
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=200)),
                ('waktu', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='pegawai.Pegawai')),
            ],
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='pegawai',
        ),
        migrations.DeleteModel(
            name='Enrol',
        ),
    ]
