# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_auto_20180114_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='pegawai',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='pegawai.Pegawai'),
        ),
    ]
