# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0004_auto_20180115_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='waktu',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
