# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0006_log_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='waktu_keluar',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
