# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0007_log_terakhir_dilihat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='waktu',
            new_name='waktu_masuk',
        ),
    ]
