# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=18)),
                ('nama', models.CharField(max_length=255)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
                ('no_hp', models.CharField(max_length=15)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai', to='pegawai.Jabatan')),
            ],
        ),
    ]
