# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_akun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='nip',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='no_hp',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
